# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dotenv/all/dotenv.rbi
#
# dotenv-3.1.8

module Dotenv
  def instrument(name, payload = nil, &block); end
  def instrumenter; end
  def instrumenter=(arg0); end
  def load!(*filenames); end
  def load(*filenames, overwrite: nil, ignore: nil); end
  def modify(env = nil, &block); end
  def overload!(*filenames); end
  def overload(*filenames); end
  def overwrite!(*filenames); end
  def overwrite(*filenames); end
  def parse(*filenames, overwrite: nil, ignore: nil, &block); end
  def require_keys(*keys); end
  def restore(env = nil, safe: nil); end
  def save; end
  def update(env = nil, overwrite: nil); end
  extend Dotenv
end
module Dotenv::Substitutions
end
module Dotenv::Substitutions::Variable
  def self.call(value, env); end
end
module Dotenv::Substitutions::Command
  def self.call(value, _env); end
end
class Dotenv::FormatError < SyntaxError
end
class Dotenv::Parser
  def call; end
  def existing?(key); end
  def expand_newlines(value); end
  def initialize(string, overwrite: nil); end
  def parse_value(value); end
  def self.call(*, **, &); end
  def self.substitutions; end
  def unescape_characters(value); end
end
class Dotenv::Environment < Hash
  def filename; end
  def initialize(filename, overwrite: nil); end
  def load; end
  def overwrite; end
  def read; end
end
class Dotenv::Error < StandardError
end
class Dotenv::MissingKeys < Dotenv::Error
  def initialize(keys); end
end
class Dotenv::Diff
  def a; end
  def added; end
  def any?; end
  def b; end
  def changed; end
  def env; end
  def initialize(a: nil, b: nil, &block); end
  def removed; end
  def snapshot; end
end
