# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-validation/all/dry-validation.rbi
#
# dry-validation-1.11.1

module Dry
end
module Dry::Validation
  def self.Contract(options = nil, &); end
  def self.loader; end
  def self.macros; end
  extend Dry::Core::Extensions
  extend Dry::Validation::Macros::Registrar
  include Dry::Core::Constants
end
class Dry::Validation::InvalidKeysError < StandardError
end
class Dry::Validation::MissingMessageError < StandardError
end
class Dry::Validation::DuplicateSchemaError < StandardError
end
class Dry::Validation::SchemaMissingError < StandardError
  def initialize(klass); end
end
class Dry::Validation::Function
  def map_keywords(block); end
  extend Dry::Initializer
  include Anonymous_Module_37
  include Dry::Initializer::Mixin::Root
end
module Anonymous_Module_37
  def __dry_initializer_config__; end
  def __dry_initializer_initialize__(*, **__dry_initializer_options__); end
  def block; end
  def block_options; end
  extend Dry::Initializer::Mixin::Local
end
module Anonymous_Module_38
  def __dry_initializer_config__; end
  def __dry_initializer_initialize__(name, *, **__dry_initializer_options__); end
  def args; end
  def block; end
  def name; end
  extend Dry::Initializer::Mixin::Local
end
class Dry::Validation::Macro < Dry::Validation::Function
  def extract_block_options(options); end
  def with(args); end
  include Anonymous_Module_38
end
module Dry::Validation::Macros
  def self.[](name); end
  def self.container; end
  def self.register(*, **, &); end
end
module Dry::Validation::Macros::Registrar
  def register_macro(*, **, &); end
end
class Dry::Validation::Macros::Container
  def config; end
  def register(name, *args, &block); end
  extend Anonymous_Dry_Configurable_Extension_39
  extend Dry::Configurable
  extend Dry::Configurable::ClassMethods
  extend Dry::Core::Container::Configuration
  include Dry::Core::Container::Mixin
end
module Anonymous_Dry_Configurable_Extension_39
end
