# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-schema/all/dry-schema.rbi
#
# dry-schema-1.14.1

module Dry
end
module Dry::Schema
  def self.Form(**options, &); end
  def self.JSON(**options, &); end
  def self.Params(**options, &); end
  def self.config; end
  def self.define(*, **, &); end
  def self.loader; end
  extend Dry::Core::Extensions
end
