# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-struct/all/dry-struct.rbi
#
# dry-struct-1.8.0

module Dry
  def self.Struct(attributes = nil, &block); end
end
class Dry::Struct
  def [](name); end
  def __attributes__; end
  def __new__(changeset); end
  def attributes; end
  def deconstruct_keys(_keys); end
  def initialize(attributes); end
  def inspect; end
  def new(changeset); end
  def self.loader; end
  def self.prepend(*arg0); end
  def to_h; end
  def to_hash; end
  extend Anonymous_Dry_Core_Deprecations_Tagged_31
  extend Anonymous_Dry_Core_Deprecations_Tagged_33
  extend Anonymous_Module_32
  extend Anonymous_Module_35
  extend Anonymous_Module_36
  extend Dry::Core::Deprecations::Interface
  extend Dry::Core::Deprecations::Interface
  extend Dry::Core::Extensions
  extend Dry::Struct::ClassInterface
  include Anonymous_Dry_Core_Equalizer_34
  include Dry::Core::Constants
  include Dry::Core::Equalizer::Methods
end
module Dry::Struct::ClassInterface
  def ===(other); end
  def abstract; end
  def attribute(name, type = nil, &); end
  def attribute?(*args, &); end
  def attribute_names; end
  def attributes(new_schema); end
  def attributes_from(struct); end
  def build_type(name, type = nil, &); end
  def call_safe(input, &); end
  def call_unsafe(input); end
  def check_schema_duplication(new_keys); end
  def constrained?; end
  def constructor(constructor = nil, **, &block); end
  def default?; end
  def default_attributes(default_schema = nil); end
  def define_accessors(keys); end
  def failure(*args); end
  def has_attribute?(key); end
  def load(attributes); end
  def meta(meta = nil); end
  def new(attributes = nil, safe = nil, &); end
  def optional?; end
  def primitive; end
  def primitive?(other); end
  def result(klass, *args); end
  def struct?(type); end
  def struct_builder; end
  def success(*args); end
  def to_ast(meta: nil); end
  def to_proc; end
  def transform_keys(proc = nil, &block); end
  def transform_types(proc = nil, &block); end
  def try(input); end
  def try_struct(input); end
  def valid_method_name?(key); end
  def |(type); end
  include Dry::Core::ClassAttributes
  include Dry::Types::Builder
  include Dry::Types::Type
end
class Dry::Struct::Error < Dry::Types::CoercionError
end
class Dry::Struct::RepeatedAttributeError < ArgumentError
  def initialize(key); end
end
class Dry::Struct::MissingAttributeError < KeyError
  def initialize(attribute:, klass:); end
end
class Dry::Struct::RecycledStructError < RuntimeError
  def initialize; end
end
class Dry::Struct::Sum < Dry::Types::Sum::Constrained
  def ===(value); end
  def call(input); end
  def try(input); end
  def try_struct(input, &block); end
  def |(type); end
end
class Dry::Struct::Constructor < Dry::Types::Constructor
  def primitive; end
end
module Dry::Types
end
class Dry::Types::Printer
  def visit_struct_constructor(constructor); end
  def visit_struct_sum(sum); end
end
module Anonymous_Dry_Core_Deprecations_Tagged_31
end
class Dry::Struct::Value < Dry::Struct
  def self.new(*); end
end
module Anonymous_Module_32
  def const_missing(missing); end
end
module Anonymous_Dry_Core_Deprecations_Tagged_33
end
module Anonymous_Dry_Core_Equalizer_34
  def cmp?(comparator, other); end
  def freeze; end
  def hash; end
end
module Anonymous_Module_35
  def inherited(klass); end
  def schema(value = nil); end
end
module Anonymous_Module_36
  def abstract_class(value = nil); end
  def inherited(klass); end
end
