# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-auto_inject/all/dry-auto_inject.rbi
#
# dry-auto_inject-1.1.0

module Dry
  def self.AutoInject(container, options = nil); end
end
module Dry::AutoInject
  def self.loader; end
end
