# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rackup/all/rackup.rbi
#
# rackup-2.2.1

module Rackup
end
module Rackup::Handler
  def self.[](name); end
  def self.default; end
  def self.get(name); end
  def self.pick(server_names); end
  def self.register(name, klass); end
  def self.require_handler(prefix, const_name); end
end
class Rackup::Server
  def app; end
  def build_app(app); end
  def build_app_and_options_from_config; end
  def build_app_from_string; end
  def check_pid!; end
  def daemonize_app; end
  def default_options; end
  def exit_with_pid(pid); end
  def handle_profiling(heapfile, profile_mode, filename); end
  def initialize(options = nil); end
  def make_profile_name(filename); end
  def middleware; end
  def opt_parser; end
  def options; end
  def options=(arg0); end
  def parse_options(args); end
  def self.default_middleware_by_environment; end
  def self.logging_middleware; end
  def self.middleware; end
  def self.start(options = nil); end
  def server; end
  def start(&block); end
  def wrapped_app; end
  def write_pid; end
end
class Rackup::Server::Options
  def handler_opts(options); end
  def parse!(args); end
end
